name: Gradle Package

on:
  release:
    types: [created]
  workflow_dispatch:
    inputs:
      name:
        description: 'Github Actions - Release'
        required: true
        default: 'Github Actions - Release'


jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        server-id: GitHubPackages # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file
        cache: 'gradle'
    - name: Publish to GitHub Packages
      run: ./gradlew publish --no-daemon
      env:
        ORG_GRADLE_PROJECT_ossrhUsername: ${{ secrets.OSSRH_USERNAME }}
        ORG_GRADLE_PROJECT_ossrhPassword: ${{ secrets.OSSRH_PASSWORD }}
        ORG_GRADLE_PROJECT_signingKey: ${{ secrets.GPG_PRIVATE_KEY }}
        ORG_GRADLE_PROJECT_signingPassword: ${{ secrets.PASSPHRASE }}
        ORG_GRADLE_PROJECT_githubActor: ${{ github.actor }}
        ORG_GRADLE_PROJECT_githubToken: ${{ secrets.GITHUB_TOKEN }}
